export const columns = [
  {
    field: "name",
    headerName: "종목명",
    flex: 1,
    hideable: false,
    defaultChecked: true,
  },
  // stock info
  {
    field: "volume",
    headerName: "거래량",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: true,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "price",
    headerName: "현재가",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: true,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "open",
    headerName: "시가",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "close",
    headerName: "종가",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "high",
    headerName: "고가",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "low",
    headerName: "저가",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  //etc
  {
    field: "foreignRate",
    headerName: "외국인비율(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },

  //finance statements
  {
    field: "marketCap",
    headerName: "시가총액(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: true,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "asset",
    headerName: "자산총계(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "debt",
    headerName: "부채총계(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "sales",
    headerName: "매출액(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "salesGrowthRate",
    headerName: "매출액증가율(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "profit",
    headerName: "영업이익(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "profitGrowthRate",
    headerName: "영업이익증가율(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "income",
    headerName: "당기순이익(억)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "divide",
    headerName: "보통주배당금(원)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },

  // invest indicators
  {
    field: "EPS",
    headerName: "EPS",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "PER",
    headerName: "PER(배)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "ROE",
    headerName: "ROE(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "ROA",
    headerName: "ROA(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "PBR",
    headerName: "PBR(배)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "retentionRate",
    headerName: "유보율(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
  {
    field: "divideRate",
    headerName: "배당율(%)",
    flex: 1,
    type: "number",
    hideable: false,
    defaultChecked: false,
    headerAlign: "left",
    align: "left",
  },
];

export let initColumns = Object.fromEntries(
  columns.map((x) => [x.field, x.defaultChecked])
);
